### ISSUE TITLE
UUID as column type and Indexing

### ISSUE THREAD

**Issue by abarrak** [LendingHome/zero_downtime_migrations#14]
It's been advised that `add_index` is not safe during deployment migration.

I wonder it this applies too on implicit column creations with `:uuid` type in Rails:

```ruby
add_columns :notebooks, :user_id, :uuid
```

**Comment by shuber** [comment]
I think it's only an issue if you [add a column with a default](https://github.com/LendingHome/zero_downtime_migrations#adding-a-column-with-a-default) but we have a documented work around for creating the column then backporting UUID values for all the existing data in batches.
