### ISSUE TITLE
Wrong advice when looping through `ActiveRecord::Base` objects

### ISSUE THREAD

**Issue by juandazapata** [LendingHome/zero_downtime_migrations#18]
As per `README.md`

```md
### Looping thru `ActiveRecord::Base` objects

#### Bad

This might accidentally load tens or hundreds of thousands of records into memory all at the same time!


  class BackportPublishedDefaultOnPosts < ActiveRecord::Migration[5.0]
    def change
      Post.all.each do |post|
        post.update_attribute(published: true)
      end
    end
  end

#### Good

Let's use the `find_each` method to fetch records in batches instead.

  class BackportPublishedDefaultOnPosts < ActiveRecord::Migration[5.0]
    def change
      Post.all.find_each do |post|
        post.update_attribute(published: true)
      end
    end
  end
```

---

The advice is wrong, because `find_each` doesn't have any effect when running inside migrations (unless we `disable_ddl_transaction!`) because Rails wraps every migration inside a database transaction.

### In reality, both examples have the same effect and both of them accidentally load tens or hundreds of thousands of records into memory all at the same time!

**Comment by kronn** [comment]
Interesting. I have not observed this limitation. My understanding was that, although eventually all records will be loaded, it happens only in batches, leaving earlier batches for the GC to collect. How have you found this behaviour?

**Comment by shuber** [comment]
Correct - records are loaded in batches in this case and GC'd periodically. We actually introduced this validation when we were investigating why a migration was failing due to "out of memory" errors. Loading ALL records in the table via `SomeModel.all` ended up being the culprit.
